//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAPTZACS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE_ZONE
    {
        public string Route_Start { get; set; }
        public string Route_End { get; set; }
        public string Zone_Name { get; set; }
        public string Zone_Id { get; set; }
    }
}
